on:
  push:
    branches:
      - master

jobs:
  variables:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      pwd: ${{ steps.set-pwd.outputs.pwd }}
    steps:
    - id: set-pwd
      run: echo "::set-output name=pwd::$(pwd)"
    - id: set-matrix
      run: echo "::set-output name=matrix::[$(find . -iname 'PKGBUILD' -exec bash -c \"basename \\$(dirname \\"{}\\")\" \; | jq -R -s -c 'split(\"\n\")[:-1]')]"

  build-packages:
    runs-on: "ubuntu-latest"
    needs: variables
    container:
      image: nubs/arch-build
      options: --privileged
      volumes:
        - ${{ needs.variables.outputs.pwd }}:/package
        - /sys/fs/cgroup:/sys/fs/cgroup

    strategy:
      matrix:
        package: ${{fromJson(needs.variables.outputs.matrix)}}
    
    steps:
    - uses: actions/checkout@v2
    - name: Build Package ${{ matrix.package }}
      working-directory: ${{ matrix.package }}
      run: makepkg -C -c --config ../makepkg.conf
    - uses: actions/upload-artifact@v3
      with:
        name: packages
        path: docs/pkg/${{ matrix.package }}*
        retention-days: 1
  
  build-repo:
    runs-on: "ubuntu-latest"
    container:
      image: nubs/arch-build
      options: --privileged
      volumes:
        - ${{ needs.variables.outputs.pwd }}:/package
        - /sys/fs/cgroup:/sys/fs/cgroup
    needs: build-packages

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v3
      with:
        name: packages
    - name: "Create Repo"
      working-directory: docs
      run: repo-add -R -n -q jckimble.db.tar.xz pkg/*
    - name: "Commit and Push Packages"
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add docs
        git commit -m "Add Packages"
        git push -u origin master