on:
  push:
    branches:
      - master

jobs:
  build-packages:
    runs-on: "ubuntu-latest"
    container:
      image: nubs/arch-build
      options: --privileged
      volumes:
        - $(pwd):/package
        - /sys/fs/cgroup:/sys/fs/cgroup

    strategy:
      matrix:
        package: [google-chrome,holo,holo-build,kr-bin,ngrok,pacrepo-cli,visual-studio-code-bin,yay]
    
    steps:
    - uses: actions/checkout@v2
    - name: Build Package ${{ matrix.package }}
      working-directory: ${{ matrix.package }}
      run: makepkg -C -c --config ../makepkg.conf
    - uses: actions/upload-artifact@v3
      with:
        name: packages
        path: docs/pkg/${{ matrix.package }}*
        retention-days: 1
  
  build-repo:
    runs-on: "ubuntu-latest"
    container:
      image: nubs/arch-build
      options: --privileged
      volumes:
        - $(pwd):/package
        - /sys/fs/cgroup:/sys/fs/cgroup
    needs: build-packages

    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v3
      with:
        name: packages
    - name: "Create Repo"
      working-directory: docs
      run: repo-add -R -n -q jckimble.db.tar.xz pkg/*
    - name: "Commit and Push Packages"
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add docs
        git commit -m "Add Packages"
        git push -u origin master